replicaCount: 1
hostname: iska.feddema.dev

image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: ""

resources:
    requests:
        cpu: 100m
        memory: 128Mi
    limits:
        cpu: 200m
        memory: 256Mi

htmlContent: |
  <html>
    <head><title>Hello from the base chart!</title></head>
    <body><h1>It works!</h1></body>
  </html>
