replicaCount: 1

hostname: ''
environment: ''
region: ''
domain: feddema.dev

image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: "1.27.5"

resources:
    requests:
        cpu: 100m
        memory: 128Mi
    limits:
        cpu: 200m
        memory: 256Mi

appContent: |
  <html>
    <body><h1>Hello from the base chart!</h1></body>
  </html>
