apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
  labels:
    demo: yes
spec:
  replicas: 1
  selector:
    matchLabels:
      demo: yes
  template:
    metadata:
      labels:
        demo: yes
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources: {}
