apiVersion: v1
kind: Namespace
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: production:/Namespace:/production
  name: production
---
apiVersion: v1
data:
  index.html: |-
    <html>
      <body><h1>Hello from production!</h1></body>
    </html>
kind: ConfigMap
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: production:/ConfigMap:production/production-demo-html
  name: production-demo-html
  namespace: production
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: production:/Service:production/production-demo
  labels:
    app.kubernetes.io/instance: production
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: demo
    app.kubernetes.io/version: 1.16.0
    helm.sh/chart: demo-0.1.0
  name: production-demo
  namespace: production
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app.kubernetes.io/instance: production
    app.kubernetes.io/name: demo
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: production:apps/Deployment:production/production-demo
  labels:
    app.kubernetes.io/instance: production
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: demo
    app.kubernetes.io/version: 1.16.0
    helm.sh/chart: demo-0.1.0
  name: production-demo
  namespace: production
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/instance: production
      app.kubernetes.io/name: demo
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: production
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: demo
        app.kubernetes.io/version: 1.16.0
        helm.sh/chart: demo-0.1.0
    spec:
      containers:
        - image: nginx:1.16.0
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /
              port: http
          name: demo
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: html-volume
      volumes:
        - configMap:
            name: production-demo-html
          name: html-volume
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: production:gateway.networking.k8s.io/HTTPRoute:production/production-demo
  name: production-demo
  namespace: production
spec:
  hostnames:
    - production.feddema.dev
  parentRefs:
    - name: envoy-gateway-public
      namespace: envoy-gateway
      sectionName: web-https
  rules:
    - backendRefs:
        - name: production-demo
          port: 80
