apiVersion: v1
kind: Service
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: dry-source:/Service:/dry-source-demo
  labels:
    app.kubernetes.io/instance: dry-source
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: demo
    app.kubernetes.io/version: 1.16.0
    helm.sh/chart: demo-0.1.0
  name: dry-source-demo
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app.kubernetes.io/instance: dry-source
    app.kubernetes.io/name: demo
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: dry-source:apps/Deployment:/dry-source-demo
  labels:
    app.kubernetes.io/instance: dry-source
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: demo
    app.kubernetes.io/version: 1.16.0
    helm.sh/chart: demo-0.1.0
  name: dry-source-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: dry-source
      app.kubernetes.io/name: demo
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: dry-source
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: demo
        app.kubernetes.io/version: 1.16.0
        helm.sh/chart: demo-0.1.0
    spec:
      containers:
        - image: nginx:1.16.0
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /
              port: http
          name: demo
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: http
