apiVersion: v1
kind: Namespace
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: development:/Namespace:/development
  name: development
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: development:/Service:development/development-demo
  labels:
    app.kubernetes.io/instance: development
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: demo
    app.kubernetes.io/version: 1.16.0
    helm.sh/chart: demo-0.1.0
  name: development-demo
  namespace: development
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app.kubernetes.io/instance: development
    app.kubernetes.io/name: demo
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: development:apps/Deployment:development/development-demo
  labels:
    app.kubernetes.io/instance: development
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: demo
    app.kubernetes.io/version: 1.16.0
    helm.sh/chart: demo-0.1.0
  name: development-demo
  namespace: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: development
      app.kubernetes.io/name: demo
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: development
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: demo
        app.kubernetes.io/version: 1.16.0
        helm.sh/chart: demo-0.1.0
    spec:
      containers:
        - image: nginx:1.16.0
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /
              port: http
          name: demo
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: development:gateway.networking.k8s.io/HTTPRoute:development/development-demo
  name: development-demo
  namespace: development
spec:
  hostnames:
    - dev.feddema.dev
  parentRefs:
    - name: envoy-gateway-public
      namespace: envoy-gateway
      sectionName: web-https
  rules:
    - backendRefs:
        - name: development-demo
          port: 80
