apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "demo.fullname" . }}
  namespace: {{ .Release.Name }}
spec:
  parentRefs:
    - name: envoy-gateway-public
      namespace: envoy-gateway
      sectionName: web-https
  hostnames:
    - {{ include "demo.hostname"}}
  rules:
    - backendRefs:
        - name: {{ include "demo.fullname" . }}
          port: 80
