apiVersion: promoter.argoproj.io/v1alpha1
kind: PromotionStrategy
metadata:
  name: demo
  namespace: promoter-system
spec:
  environments:
    - autoMerge: true
      branch: environments/development
    - autoMerge: false
      branch: environments/staging
    - autoMerge: false
      branch: environments/production
  gitRepositoryRef:
    name: demo-repo
